services: 
  web1: 
    image: nginx:latest
    ports: 
      - 8080:80
    volumes:
      - ./html/index.html:/usr/share/nginx/index.html
  
  # web2: 
  #   image: nginx:latest 
  #   ports: 
  #     - 8060:80
  #   volumes:
  #     - ./html/main.html:/usr/share/nginx/html
    
  # redis: 
  #   image: redis:latest 
  #   # ports: 
    