apiVersion: apps/v1
kind: Deployment

metadata:
  name: website-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      app: website

  template:
    metadata:
      labels:
        app: website

    spec:
      containers:
      - name: website-container
        image: selfheal:v1
        imagePullPolicy: Never

        ports:
        - containerPort: 80